name: Create_new_subscribe_CI

on: 
  release:
    types: [published]

  push:
   branches: 
     - master

  schedule:
    - cron: 0 7 * * 1,4,6
  
  #watch:
  #  types: [started]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Run python vmessviews.py
      run: |
        echo -e "Download gistsub.txt"
        wget https://gist.githubusercontent.com/cutelua/e51eb3408409adc6bbb9d11246bea623/raw/txt -O gistsub.txt
        cat gistsub.txt | python3 vmessviewer.py --hide --addws
    - name: Run push a new branch
      run: |
        echo -e "push new subscribe file"
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git branch download_branch 
        git add .
        git commit -m 'Auto Pushd From Action'
        git push --force https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git master:download_branch
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: new_subcribe
        path: file
